version: "3.8"

services:
  backend:
    build: .
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - fastapi
      - recommendation-api
    command: nodemon
    env_file:
      - .env

  fastapi:
    build:
      context: ./fast_api
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fast_api:/app    # ✅ bien dans un array YAML
    environment:
      - PYTHONUNBUFFERED=1

  recommendation-api:
    build:
      context: ./recommendation_api
      dockerfile: Dockerfile
    container_name: recommendation_api
    ports:
      - "${RECOMMENDATION_API_PORT}:8001"
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db

volumes:
  pgdata:
